# ===================================================================
# CONFIGURACIÓN BASE (Común para todos los perfiles)
# ===================================================================
server:
  port: 8088

spring:
  main:
    web-application-type: reactive

---
# ===================================================================
# PERFIL DE DOCKER (Para desarrollo local)
# ===================================================================
spring:
  config:
    activate:
      on-profile: "docker"
  cloud:
    gateway:
      routes:
        - id: guias_route_local
          uri: http://guia-service:8080
          predicates:
            - Path=/api/v1/guias/**
          filters:
            - StripPrefix=3
            
        - id: guias_docs_local
          uri: http://guia-service:8080
          predicates:
            - Path=/v3/api-docs/guias_route_local
          filters:
            - RewritePath=/v3/api-docs/guias_route_local, /v3/api-docs
  
springdoc:
  swagger-ui:
    urls:
      - name: Servicio de Guías
        url: /v3/api-docs/guias_route_local

---
# ===================================================================
# PERFIL DE PRODUCCIÓN (Para Render)
# ===================================================================
spring:
  config:
    activate:
      on-profile: "prod"

springdoc:
  swagger-ui:
    urls:
      - name: Servicio de Guías
        url: /v3/api-docs/guias_route_prod